[package]
name = "gc-rs"
version = "0.1.0"
authors = ["gtash"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
parking_lot = "0.9"
lazy_static = "1.3"
time = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser","memoryapi","errhandlingapi"] }
kernel32-sys = "0.2"