[package]
name = "cgc"
version = "0.2.6"
authors = ["gtash"]
edition = "2018"
description = "Copying garbage collector"
repository = "https://github.com/playXE/cgc"
readme = "README.md"
keywords = ["gc","garbage-collector"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
parking_lot = "0.9"
lazy_static = "1.3"
time = "0.1"
hashlink = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser","memoryapi","errhandlingapi"] }
kernel32-sys = "0.2"